import Head from "next/head";
import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import api from "@/api/service/coin";
import { Box, Layout, List, SearchBar } from "@/component";
import { useState } from "react";
import { IAllCoinProps } from "@/types/res";


export const getServerSideProps: GetServerSideProps = async () => {
  const { data: coin } = await api.getCoin({
    vs_currency: "brl",
    locale: "en",
    order: "market_cap_desc",
    page: 1,
    per_page: 50,
    sparkline: false,
  });
  if (!coin) {
    return {
      notFound: true,
    };
  }
  return {
    props: {
      coin: coin,
    },
  };
};

const Home = ({
  coin,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  const [query, setQuery] = useState<string>("");
  let data = coin?.filter((item: IAllCoinProps) => {
    if (query == "") {
      return item;
    } else if (
      item.name.toLocaleLowerCase().includes(query.toLocaleLowerCase())
    ) {
      return item;
    }
  });
  const onChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setQuery(event.target.value);
  };
  return (
    <>
      <Head>
        <title>Tehran Payment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout data-testid='wrapper'>
        <SearchBar value={query} placeholder="Search" onChange={onChange} />
        <Box>
          <List item={data} />
        </Box>
      </Layout>
    </>
  );
}
export default Home;